@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


@echo off 

if not "%~1" == "" goto debugFile 

@echo on 

"D:\iar\common\bin\cspybat" -f "D:\1.intelligent vehicle\3、MK60母板VE2（配套VG核心板）\LQ_MK60_VE2母板资料\2. 参考例程\新版例程20190517\11.龙邱K60 TFT1.8例程\11.龙邱K60 TFT1.8例程\settings\LQ_K60.MK60DN.general.xcl" --backend -f "D:\1.intelligent vehicle\3、MK60母板VE2（配套VG核心板）\LQ_MK60_VE2母板资料\2. 参考例程\新版例程20190517\11.龙邱K60 TFT1.8例程\11.龙邱K60 TFT1.8例程\settings\LQ_K60.MK60DN.driver.xcl" 

@echo off 
goto end 

:debugFile 

@echo on 

"D:\iar\common\bin\cspybat" -f "D:\1.intelligent vehicle\3、MK60母板VE2（配套VG核心板）\LQ_MK60_VE2母板资料\2. 参考例程\新版例程20190517\11.龙邱K60 TFT1.8例程\11.龙邱K60 TFT1.8例程\settings\LQ_K60.MK60DN.general.xcl" "--debug_file=%~1" --backend -f "D:\1.intelligent vehicle\3、MK60母板VE2（配套VG核心板）\LQ_MK60_VE2母板资料\2. 参考例程\新版例程20190517\11.龙邱K60 TFT1.8例程\11.龙邱K60 TFT1.8例程\settings\LQ_K60.MK60DN.driver.xcl" 

@echo off 
:end