param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "D:\iar\common\bin\cspybat" -f "D:\1.intelligent vehicle\3、MK60母板VE2（配套VG核心板）\LQ_MK60_VE2母板资料\2. 参考例程\新版例程20190517\11.龙邱K60 TFT1.8例程\11.龙邱K60 TFT1.8例程\settings\LQ_K60.MK60DN.general.xcl" --backend -f "D:\1.intelligent vehicle\3、MK60母板VE2（配套VG核心板）\LQ_MK60_VE2母板资料\2. 参考例程\新版例程20190517\11.龙邱K60 TFT1.8例程\11.龙邱K60 TFT1.8例程\settings\LQ_K60.MK60DN.driver.xcl" 
}
else
{
& "D:\iar\common\bin\cspybat" -f "D:\1.intelligent vehicle\3、MK60母板VE2（配套VG核心板）\LQ_MK60_VE2母板资料\2. 参考例程\新版例程20190517\11.龙邱K60 TFT1.8例程\11.龙邱K60 TFT1.8例程\settings\LQ_K60.MK60DN.general.xcl" --debug_file=$debugfile --backend -f "D:\1.intelligent vehicle\3、MK60母板VE2（配套VG核心板）\LQ_MK60_VE2母板资料\2. 参考例程\新版例程20190517\11.龙邱K60 TFT1.8例程\11.龙邱K60 TFT1.8例程\settings\LQ_K60.MK60DN.driver.xcl" 
}
